### ISSUE TITLE
fix: inconsistent redirect behaviour when searching a specific card

### ISSUE THREAD

**Issue by NipulM** [Statcraftlk/Game-stat-analysis-app#11]
When users search for a specific card, the redirect behaviour is inconsistent. It only works if the user is on the 'View all cards' page. Otherwise, it does not redirect to a new page and instead remains on the current page, which is not ideal.

![Screenshot 2024-02-11 at 13 19 50](https://github.com/Statcraftlk/Game-stat-analysis-Frontend/assets/125451160/1adc1455-e4f5-4899-b411-f9c88aea68e2)

**Comment by randilt** [comment]
![image](https://github.com/Statcraftlk/Game-stat-analysis-Frontend/assets/51049280/f325f297-cae5-4141-bcba-09ee92c4aede)
Instead of redirecting the user, fixed it by showing the filter option only if the user is currently in the "/all-cards" route.
![image](https://github.com/Statcraftlk/Game-stat-analysis-Frontend/assets/51049280/5344f574-73ce-418e-94ef-75c659dd6c10)
